(() => {
const data=window.SITE_CONTENT;
let lang='zh';try{lang=localStorage.getItem('yijun-language')==='en'?'en':'zh'}catch(_){}
const text=v=>typeof v==='string'?v:v?.[lang]||'';
function element(tag,cls,value){const n=document.createElement(tag);if(cls)n.className=cls;if(value)n.textContent=value;return n}
function timeline(items,id){document.getElementById(id).replaceChildren(...items.map(item=>{const a=element('article','timeline-item'),meta=element('div','meta');meta.append(element('span','date',text(item.date)));if(item.current)meta.append(element('span','current',text(data.copy.current)));a.append(meta,element('h4','',text(item.title)),element('p','role',text(item.role)),element('p','place',text(item.place)),element('p','description',text(item.description)));if(item.details){const d=element('details');d.append(element('summary','',text(data.copy.details)),element('p','description',text(item.details)));a.append(d)}return a}))}
function render(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-copy]').forEach(n=>n.textContent=text(data.copy[n.dataset.copy]));const b=document.getElementById('language');b.textContent=lang==='zh'?'EN ↗':'中文 ↗';b.setAttribute('aria-label',lang==='zh'?'Switch to English':'切换到中文');document.querySelector('.cover').alt=lang==='zh'?'刘一骏在金门大桥前':'Yijun Liu in front of the Golden Gate Bridge';document.querySelector('.postcard img').alt=lang==='zh'?'金门大桥与海湾':'The Golden Gate Bridge and the bay';timeline(data.education,'education-list');timeline(data.experience,'experience-list');const extra=document.getElementById('additional-sections');extra.replaceChildren();data.sections.forEach(s=>{const section=element('section','additional-section');section.append(element('h3','',text(s.title)),element('p','',text(s.text)));const gallery=element('div','gallery');(s.photos||[]).forEach(p=>{const f=element('figure'),img=element('img');img.src=p.src;img.alt=text(p.alt);img.loading='lazy';f.append(img,element('figcaption','',text(p.caption)));gallery.append(f)});section.append(gallery);extra.append(section)})}
document.getElementById('language').addEventListener('click',()=>{lang=lang==='zh'?'en':'zh';try{localStorage.setItem('yijun-language',lang)}catch(_){}render()});document.getElementById('year').textContent=new Date().getFullYear();render();
})();
