// Public content only. Keep both translations up to date.
window.SITE_CONTENT = {
copy: {
navAbout:{zh:'关于',en:'About'},navJourney:{zh:'我的足迹',en:'Journey'},navBeyond:{zh:'生活切片',en:'Beyond'},
tagline:{zh:'保持好奇，走向更广阔的世界。',en:'Stay curious. Find a wider world.'},discover:{zh:'慢慢认识我',en:'Get to know me'},opening:{zh:'一段旅程的开篇',en:'An unfolding story'},
aboutTitle:{zh:'在理性与好奇之间，\n探索自己的坐标。',en:'Rooted in thought.\nOpen to discovery.'},
bio:{zh:'我是刘一骏，目前在哥伦比亚大学攻读运筹学硕士。本科就读于四川大学，学习计算机科学与技术，并辅修金融工程。从成都到纽约，从课堂到投资与资本市场的实践，我在不同的视角中积累对世界的理解。这里也会记录沿途的风景，以及生活中不断生长的好奇。',en:'I’m Yijun Liu, pursuing a master’s in Operations Research at Columbia University. I studied Computer Science and Technology with a minor in Financial Engineering at Sichuan University. From Chengdu to New York, from the classroom to investment research and capital markets, I’m finding new perspectives along the way. This is also a home for the places, moments, and curiosities that make up life beyond work.'},
onward:{zh:'继续探索 ↗',en:'AND ONWARD ↗'},journeyTitle:{zh:'一路走来',en:'The journey so far'},journeyNote:{zh:'在学习中拓宽视野，在实践中理解世界。',en:'Perspectives shaped by learning and experience.'},education:{zh:'教育经历',en:'Education'},experience:{zh:'实习经历',en:'Experience'},
beyondTitle:{zh:'生活，不止一面',en:'More than one perspective'},beyondNote:{zh:'给风景、偶然与新的热爱，留一点位置。',en:'A little room for places, moments, and new interests.'},photoTitle:{zh:'风从海湾吹来',en:'A breeze across the bay'},moreTitle:{zh:'故事还在继续。',en:'Still more to discover.'},moreText:{zh:'未来的风景、镜头里的瞬间，还有日常中值得记下的小事。慢慢收集，慢慢分享。',en:'Places yet to see, moments to capture, and small things worth remembering. A collection that grows along the way.'},travel:{zh:'旅行',en:'Travel'},photography:{zh:'摄影',en:'Photography'},everyday:{zh:'日常',en:'Everyday'},footer:{zh:'保持好奇，未完待续。',en:'Stay curious. More to come.'},backTop:{zh:'回到顶部 ↑',en:'Back to top ↑'},details:{zh:'展开经历',en:'Read more'},current:{zh:'进行中',en:'Current'}
},
education:[
{date:{zh:'2025.09 — 2026.12（预计）',en:'SEP 2025 — DEC 2026 (EXPECTED)'},title:{zh:'哥伦比亚大学',en:'Columbia University'},role:{zh:'运筹学 · 理学硕士',en:'M.S. in Operations Research'},place:{zh:'纽约，美国',en:'New York, US'},description:{zh:'在优化、随机模型与金融应用之间，探索复杂问题的解法。',en:'Exploring complex problems through optimization, stochastic models, and financial applications.'},details:{zh:'主要课程：优化模型与方法、随机模型、人工智能金融应用、金融工程应用编程、模拟与仿真。',en:'Selected coursework: optimization models and methods, stochastic models, AI in finance, programming for financial engineering, and simulation.'}},
{date:{zh:'2021.09 — 2025.06',en:'SEP 2021 — JUN 2025'},title:{zh:'四川大学',en:'Sichuan University'},role:{zh:'计算机科学与技术 · 工学学士\n金融工程（辅修）· 经济学学士',en:'B.Eng. in Computer Science and Technology\nB.Econ. in Financial Engineering (minor)'},place:{zh:'成都，中国',en:'Chengdu, China'},description:{zh:'计算金融交叉试验班，在计算机科学与金融的交汇处打下基础。',en:'An interdisciplinary foundation at the intersection of computing and finance.'}}
],
experience:[
{date:{zh:'2026.08 — 至今',en:'AUG 2026 — PRESENT'},current:true,title:{zh:'建信基金',en:'CCB Principal Asset Management'},role:{zh:'国际投资与业务发展部 · 实习生',en:'International Investment & Business Development Intern'},place:{zh:'北京，中国',en:'Beijing, China'},description:{zh:'关注海外权益市场与 AI 产业链，参与全球科技公司的基本面研究与估值分析。',en:'Researching global equities and the AI value chain, with a focus on technology company fundamentals and valuation.'},details:{zh:'参与新兴市场混合（QDII）研究，跟踪算力基础设施、芯片、服务器、云计算及应用，分析公司盈利驱动、资本开支与风险收益。',en:'Supported emerging-markets QDII research across compute infrastructure, semiconductors, servers, cloud, and applications; analyzed earnings drivers, capital expenditure, and risk-reward.'}},
{date:{zh:'2026.06 — 2026.08',en:'JUN 2026 — AUG 2026'},title:{zh:'摩根士丹利证券（中国）',en:'Morgan Stanley Securities (China)'},role:{zh:'投资银行部 · 实习生',en:'Investment Banking Intern'},place:{zh:'北京，中国',en:'Beijing, China'},description:{zh:'参与半导体、光通信及创新药行业研究，支持财务建模、估值分析与港股项目执行。',en:'Supported semiconductor, optical communications, and innovative therapeutics research, financial modeling, valuation, and Hong Kong listing execution.'},details:{zh:'梳理公司经营与竞争格局，更新收入、利润及营运资金预测，参与招股书信息核对及 A 股权益融资市场分析。',en:'Analyzed businesses and competition, updated revenue, earnings, and working-capital forecasts, reviewed prospectus disclosures, and researched A-share equity financing activity.'}},
{date:{zh:'2023.07 — 2023.08',en:'JUL 2023 — AUG 2023'},title:{zh:'中信建投证券',en:'China Securities'},role:{zh:'债券承销部 · 实习生',en:'Bond Underwriting Intern'},place:{zh:'北京，中国',en:'Beijing, China'},description:{zh:'参与公司债与企业债发行材料准备，从现金流、债务结构与期限分布理解发行人信用。',en:'Supported corporate bond offering materials and issuer credit analysis through cash flow, debt structure, and maturity profiles.'},details:{zh:'协助十余个央企及地方国企项目的募集说明书编写与更新，支持立项、尽调及问询回复。',en:'Helped prepare and update offering memoranda for more than ten state-owned enterprise bond transactions, supporting project initiation, due diligence, and review responses.'}}
],
// Add future interests, travel notes and photo galleries here. See README.md.
sections:[]
};
